version: '3.8'

services:
  collectors-dream:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - mongodb_data:/data/db
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  mongodb_data: